### PR TITLE
Fix caching when obj=None

### PR DESCRIPTION
**Pull request by bport**

### CODE REVIEW

**Comment by diefenbach** [comment]
I can't see any difference in the result. Can you elaborate?

**Comment by bport** [comment]
yes sure:
we check if obj is not none 
because ContentType.objects.get_for_model(obj) don't support None values for object

**Comment by diefenbach** [comment]
Yes, but the existing code does this also. Any problems with that?

**Comment by bport** [comment]
ctype = ContentType.objects.get_for_model(obj)

when you call this line you didn't check if obj exist

you can see stacktrace problem on this related issue:
https://github.com/diefenbach/django-permissions/issues/2

**Comment by diefenbach** [comment]
Ah, I see. Thx.

**Comment by bport** [comment]
Hi, it is possible to backport it to 1.2 branch and release a 1.2.3 version?
thanks

**Comment by diefenbach** [comment]
Sure, will do that.

**Pull request merged**
